spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/recipe_db_dev
    username: admin_dev
    password: password_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
server:
  port: 8080
